language: java
install: mvn clean install -B -V -Dintegration-tests=true -pl cloudsim-plus,cloudsim-plus-examples
script: mvn clean package
after_success:
  - mvn clean test -Dintegration-tests=true jacoco:report
  - mvn versioneye:update 
jdk:
  - oraclejdk8 

test:
  post:
    - mvn jacoco:report
    - curl http://www.jpm4j.org/install/script -k > jpmInstall.sh
    - sudo sh jpmInstall.sh
    - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
    #Upload the coverage report to codacy.com. It requires the CODACY_PROJECT_TOKEN environment variable
    - codacy-coverage-reporter -l Java -r cloudsim-plus/target/site/jacoco/jacoco.xml
